COMPONENT_ID = None

MITRE_ATTACK_ENTERPRISE = "enterprise-attack"
MITRE_ATTACK_MOBILE = "mobile-attack"
MITRE_ATTACK_ICS = "ics-attack"

LAYER_DOMAINS = {
    MITRE_ATTACK_ENTERPRISE,
    MITRE_ATTACK_MOBILE,
    MITRE_ATTACK_ICS,
}

LAYER_DOMAIN_NORMALIZATION_MAP = {
    MITRE_ATTACK_ENTERPRISE: MITRE_ATTACK_ENTERPRISE,
    MITRE_ATTACK_MOBILE: MITRE_ATTACK_MOBILE,
    MITRE_ATTACK_ICS: MITRE_ATTACK_ICS,
    "mitre-enterprise": MITRE_ATTACK_ENTERPRISE,
    "mitre-mobile": MITRE_ATTACK_MOBILE,
    "mitre-ics": MITRE_ATTACK_ICS,
}

PRE = "PRE"
WINDOWS = "Windows"
LINUX = "Linux"
MACOS = "macOS"
NETWORK = "Network"
AWS = "AWS"
GCP = "GCP"
AZURE = "Azure"
AZURE_AD = "Azure AD"
OFFICE_365 = "Office 365"
SAAS = "SaaS"

ANDROID = "Android"
IOS = "iOS"

CONTROL_SERVER = "Control Server"
DATA_HISTORIAN = "Data Historian"
ENGINEERING_WORKSTATION = "Engineering Workstation"
FIELD_CONTROLLER_RTU_PLC_IED = "Field Controller/RTU/PLC/IED"
HUMAN_MACHINE_INTERFACE = "Human-Machine Interface"
INPUT_OUTPUT_SERVER = "Input/Output Server"
SAFETY_INSTRUMENTED_SYSTEM_PROTECTION_RELAY = (
    "Safety Instrumented System/Protection Relay"
)

PLATFORMS_BY_LAYER_DOMAIN = {
    MITRE_ATTACK_ENTERPRISE: {
        PRE,
        WINDOWS,
        LINUX,
        MACOS,
        NETWORK,
        AWS,
        GCP,
        AZURE,
        AZURE_AD,
        OFFICE_365,
        SAAS,
    },
    MITRE_ATTACK_MOBILE: {
        ANDROID,
        IOS,
    },
    MITRE_ATTACK_ICS: {
        WINDOWS,
        CONTROL_SERVER,
        DATA_HISTORIAN,
        ENGINEERING_WORKSTATION,
        FIELD_CONTROLLER_RTU_PLC_IED,
        HUMAN_MACHINE_INTERFACE,
        INPUT_OUTPUT_SERVER,
        SAFETY_INSTRUMENTED_SYSTEM_PROTECTION_RELAY,
    },
}

AVG = "average"
MIN = "min"
MAX = "max"
SUM = "sum"

LAYOUT_AGGREGATE_FUNCTIONS = [AVG, MIN, MAX, SUM]

SIDE = "side"
FLAT = "flat"
MINI = "mini"

LAYOUT_TYPES = [SIDE, FLAT, MINI]


SORT_ASCENDING_BY_TECHNIQUE_NAME = 0
SORT_DESCENDING_BY_TECHNIQUE_NAME = 1
SORT_ASCENDING_BY_TECHNIQUE_SCORE = 2
SORT_DESCENDING_BY_TECHNIQUE_SCORE = 3
